### ISSUE TITLE
Implementing examples

### ISSUE THREAD

**Issue by morukele** [morukele/paystack-rs#4]
I need help implementing examples of the API client in the /example folder.

As I build the API client and write tests; it will be nice to have examples of logic that can be done with the crate.

Some examples off the top of my head:
- A CLI app to create a transaction in your Paystack integration, the app can return the payment link generated, and you can also check the status of the transaction on the CLI using the transaction reference.
- A CLI to give the number of transactions in your integration, it can further group the transactions based on status or any other criteria you like.

These are just examples, feel free to be creative with your examples. The goal is to show what can be built with the crate.

If you create an example, please name the file after your example, this will make it intuitive for other users. It will also be nice if you comment on the code.

This is a non-ending issue, so it is opened to as many contributors as possible.

**Comment by kinglighthill** [comment]
I would like to work on this

**Comment by morukele** [comment]
Yeah please feel free to handle it;

**Comment by kinglighthill** [comment]
I have been trying to create an example for split transaction but I keep on getting this error.
`RequestNotSuccessful("400 Bad Request", "{\"status\":false,\"message\":\"Bearer subaccount must be part of split group\"}")`

**Comment by morukele** [comment]
It seems that we have to create a split group first. Can you look into this?

**Comment by kinglighthill** [comment]
Is the split group not what transaction splits create endpoint is doing

**Comment by morukele** [comment]
@kinglighthill I am not sure, I will give it a look and get back to you. I will update this issue thread.

**Comment by kinglighthill** [comment]
Ok

**Comment by kinglighthill** [comment]
Ok, thank you
